Use quotes when setting more than 1 constraint
In my recent usage of Juju 2.1.1-xenial-amd64 I found I needed to use quotes when setting more than one constraint:

arosales@x230:~$ juju deploy ubuntu --constraints mem=4G cores=2
error: invalid application name "cores=2"
arosales@x230:~$ juju deploy --constraints mem=4G cores=2 ubuntu
ERROR cannot parse URL "cores=2": name "cores=2" not valid
arosales@x230:~$ juju deploy --constraints "mem=4G cores=2" ubuntu
Located charm "cs:ubuntu-10".
Deploying charm "cs:ubuntu-10".
arosales@x230:~$ juju version
2.1.1-xenial-amd64
arosales@x230:~$ 

If this is indeed correct this pulls add quotes when using more than one constraint.